#!/usr/bin/env node
// Create the build directory and write all license variants
// to that directory.
var childProcess = require('child_process')
var fs = require('fs')
var path = require('path')

// Read the source Markdown file.
var source = fs.readFileSync('polyform.md', 'utf8')

// Filter out notes and empty lines.
var contentLines = source
  .split('\n')
  .filter(function (line) {
    return (
      line.trim().length !== 0 &&
      !line.includes('Note to Reviewers')
    )
  })

// Create the build directory.
try {
  fs.mkdirSync('build')
} catch (error) {
  if (error.code !== 'EEXIST') throw error
}

// Determine version.
var version = 'Development Draft'
try {
  childProcess.execSync('git diff-index --quiet HEAD')
  var tag = childProcess.execSync(
    'git describe --exact-match --tags 2>/dev/null'
  )
  if (tag.startsWith('v')) {
    version = 'Version ' + tag.slice(1)
  }
} catch (error) {
  // pass
}
if (process.env.VERSION) version = process.env.VERSION

// Generate variants.
var variants = {
  'Internal': [ 'CL', 'DL', 'IB' ],
  'Noncommercial': [ 'CL', 'DL' ],
  'Noncompete': [ 'CL', 'DL', 'NX' ],
  'Small': [ 'CL', 'DL', 'SB' ],
  'Strict': [],
  'Trial': [ 'CL', 'DL', 'FT' ]
}

Object.keys(variants).forEach(function (suffix) {
  var options = variants[suffix]
  if (options.includes('DL')) options.push('NO')
  var fileName = path.join(
    __dirname, 'build', 'Polyform-' + suffix + '.md'
  )
  var stream = fs.createWriteStream(fileName)
  writeVariant(stream, suffix, options)
})

function writeVariant (stream, suffix, options) {
  var skipContent = false
  // Pipe through fmt -60 -u.
  var fmt = childProcess.spawn('fmt', ['-64', '-u'])
  fmt.stdout.pipe(stream)
  var input = fmt.stdin
  contentLines.forEach(function (line) {
    if (line.startsWith('# ')) {
      input.write(
        '# Polyform ' + suffix + ' License ' + version
      )
    } else if (line.includes('{License URL}')) {
      input.write('\n\n')
      if (version.toLowerCase().includes('draft')) {
        input.write('https://github.com/polyformproject/polyform-licenses/')
      } else {
        input.write(
          'https://polyformproject.org/licenses/' +
          suffix.toLowerCase() +
          '/' + version.trim()
        )
      }
    } else if (line.startsWith('## ')) {
      skipContent = false
      // If the <h2> has a two-letter code...
      var match = /^## ([A-Z]{2}): (.+)$/.exec(line)
      if (match) {
        var code = match[1]
        var heading = match[2]
        // ... if it's part of the variant, include it.
        if (options.includes(code)) {
          input.write('\n\n## ' + heading)
        // ... otherwise skip both the heading and th
        // text that follows.
        } else {
          skipContent = true
        }
      // If the heading does not have a two-letter code,
      // write it out.
      } else {
        input.write('\n\n' + line)
      }
    } else {
      if (!skipContent) input.write('\n\n' + line)
    }
  })
  input.end('\n')
}
